---

- name: Ubuntu trusty, xenial
  block:
    - name: Ubuntu | Enable backports (replace)
      ansible.builtin.replace:
        dest: '/etc/apt/sources.list'
        regexp: '^# deb http://(.*)/ubuntu([/]*) {{ ansible_distribution_release | lower }}-backports'
        replace: 'deb http://\1/ubuntu\2 {{ ansible_distribution_release | lower }}-backports'
        mode: '0644'
        backup: yes
      register: backports1
    - name: Ubuntu | Enable backports (line)
      ansible.builtin.lineinfile:
        dest: '/etc/apt/sources.list'
        regexp: '^deb http://.*/ubuntu {{ ansible_distribution_release | lower }}-backports main restricted universe multiverse'
        line: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }}-backports main restricted universe multiverse'
        mode: '0644'
        backup: yes
      register: backports2

    - name: apt | update cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: backports1.changed or backports2.changed
      register: pkg_result
      until: pkg_result is success
    - name: apt | install of lxd from backports
      ansible.builtin.apt:
        name: lxd
        state: latest  # noqa 403
        default_release: "{{ ansible_distribution_release | lower }}-backports"
        update_cache: yes
  when: lxd_force_ubuntu_backports or ansible_distribution_release.lower() == 'trusty' or ansible_distribution_release.lower() == 'xenial'

- name: Debian | refresh apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: apt | lxd
  ansible.builtin.apt:
    name: "{{ lxd_packages }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Install lxd via snap
  community.general.snap:
    name:
      - lxd

- name: apt | zfs dependencies
  ansible.builtin.apt:
    name: zfsutils-linux
    state: present
  when: >
    lxd_with_zfs_backend is defined and lxd_with_zfs_backend and
    not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))
  register: pkg_result
  until: pkg_result is success

- name: ensure aide.conf.d directory exists
  ansible.builtin.file:
    dest: /etc/aide/aide.conf.d
    state: directory
    mode: 0755

- name: add additional aide HIDS configuration
  ansible.builtin.copy:
    src: 99_aide_local_lxd
    dest: /etc/aide/aide.conf.d/99_aide_local_lxd
    mode: 0644
