---

- name: Debian | refresh apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Debian | lxd
  ansible.builtin.apt:
    name: "{{ lxd_packages }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Install lxd via snap
  community.general.snap:
    name:
      - lxd
  when:
    - not has_pve.stat.exists

- name: Debian | zfs dependencies
  ansible.builtin.apt:
    name: zfsutils-linux
    state: present
  when: >
    lxd_with_zfs_backend is defined and lxd_with_zfs_backend and
    not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")) and
    not has_pve.stat.exists
  register: pkg_result
  until: pkg_result is success

- name: Ensure aide.conf.d directory exists
  ansible.builtin.file:
    dest: /etc/aide/aide.conf.d
    state: directory
    mode: 0755

- name: Add additional aide HIDS configuration
  ansible.builtin.copy:
    src: 99_aide_local_lxd
    dest: /etc/aide/aide.conf.d/99_aide_local_lxd
    mode: 0644
