---

# - debug: var=current
- name: Download lxc image {{ image }}  # noqa no-changed-when
  ansible.builtin.command:
    cmd: "lxc image copy {{ image }} local: --alias={{ alias }}"
  when: current is defined and current.stdout.find(alias) == -1
