---

- name: retrieve lxcfs source
  get_url:
    url: https://linuxcontainers.org/downloads/lxcfs/lxcfs-2.0.3.tar.gz
    checksum: 'sha256:dd94e19bff202cb9fe2aa7d244b2cccf53cf5d7f6dd76c815e1161e3ba4ce0df'
    dest: /root/lxcfs-2.0.3.tar.gz
    mode: '0600'

- name: uncompress lxcfs archive
  unarchive:
    src: /root/lxcfs-2.0.3.tar.gz
    dest: /root/
    mode: '0755'
  ## Cannot change ownership to uid 201105, gid 200512
  failed_when: false

- name: build lxcfs
  command: "{{ item }}"
  args:
    chdir: /root/lxcfs-2.0.3
    creates: /usr/local/lib/liblxcfs.so.0.0.0
  with_items:
    - ./configure
    - make
    - make install
