---

- block:
  - name: lxd-cluster
    command: echo

  - set_fact:
      master="{{ lookup('template', 'lxd-server.yml.j2') }}"

  - debug:
      var: master

  - name: lxd init lxd-server.yml
    command: lxd init --preseed <
    args:
      stdin: "{{ master }}"
    when: inventory_hostname == groups.lxd[0]

  - name: lxc info
    shell: lxc info
    register: lxc_info_src
    run_once: true

  - set_fact:
      lxc_info="{{ lxc_info_src.stdout | from_yaml }}"

  - debug:
      var: lxc_info.environment.certificate_fingerprint

  - set_fact:
      slaves="{{ lookup('template', 'lxd-client.yml.j2') }}"

  - debug:
      var: slaves

  - name: lxd init lxd-client.yml
    command: lxd init --preseed < 
    args:
      stdin: "{{ slaves }}"
    when: inventory_hostname != groups.lxd[0]
