---
## when Ansible 2.2.0 released: use lxd_container module

- block:
    - name: start lxc instance {{ guest }}
      ansible.builtin.shell: "{{ item }}"  # noqa 305
      with_items:
        - "lxc init {{ template }} {{ guest }}"
        - "lxc start {{ guest }}"
        ## mostly for images from linuxcontainers.org + centos, necessary for CI testing, especially travis
        ##  --stdin not supported on xenial
        # - "openssl rand -base64 48 | lxc exec {{ guest }} -- passwd root --stdin"
        - "openssl rand -base64 48 | perl -ne 'print \"$_\" x2' | lxc exec {{ guest }} -- passwd root"
      when: lxclist.stdout.find(" " + guest " ") == -1

    - name: configure lxc instance {{ guest }}  # noqa no-changed-when
      ansible.builtin.command: "lxc exec {{ guest }} -- {{ item }}"
      with_items: "{{ shellcmds }}"
      # ignore_errors: true

    - name: stop and publish lxc instance {{ guest }}  # noqa no-changed-when
      ansible.builtin.command: "{{ item }}"
      with_items:
        - "lxc stop {{ guest }} --force"
        - "lxc publish {{ guest }} --alias {{ publishalias }}"
        - "lxc delete {{ guest }}"
  when: imagelist.stdout.find(" {{ publishalias }} ") == -1
