---

- block:
  - name: lxd-cluster
    command: echo

  - name: test lxd-server.yml
    template: src=lxd-server.yml.j2 dest=/tmp/lxd-server.yml

  - name: lxd init lxd-server.yml
    command: lxd init --preseed <
    args:
      stdin: "{{ lookup('template', 'lxd-server.yml.j2') }}"
    when: inventory_hostname == groups.lxd[0]

  - name: lxc info
    shell: lxc info
    register: lxc_info_src
    run_once: true

  - set_fact:
      lxc_info="{{ lxc_info_src.stdout | from_yaml }}"

  - debug:
      var: lxc_info.environment.certificate_fingerprint

  - name: test lxd-client.yml
    template: src=lxd-client.yml.j2 dest=/tmp/lxd-client.yml

  - name: lxd init lxd-client.yml
    command: lxd init --preseed < 
    args:
      stdin: "{{ lookup('template', 'lxd-client.yml.j2') }}"
    when: inventory_hostname != groups.lxd[0]

  # - name: configure core_address
  #   command: lxc config set core.https_address {{ ansible_default_ipv4.address }}:8443

