---

- name: Debug | ansible_env
  ansible.builtin.debug:
    var: ansible_env

- name: Import travis
  ansible.builtin.import_tasks: travis.yml
  when: ansible_env['TRAVIS'] is defined and ansible_env['TRAVIS'] == 'true'

- name: Check if proxmox is present to avoid possible conflict
  ansible.builtin.stat:
    path: /etc/pve
  register: has_pve

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for Debian.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Debian'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- name: Import debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Import redhat
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 7

- name: Import redhat7
  ansible.builtin.import_tasks: redhat7.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Import lxd
  ansible.builtin.import_tasks: lxd.yml
  when:
    - not has_pve.stat.exists

- name: Configure LXD
  when:
    - not has_pve.stat.exists
  block:
    - name: Get LXD Version
      ansible.builtin.command: lxd --version
      register: lxd_version_cmd
      changed_when: false

    - name: Extract LXD version
      ansible.builtin.set_fact:
        lxd_version: "{{ lxd_version_cmd.stdout_lines[0] }}"

    - name: Import lxd-init
      ansible.builtin.import_tasks: lxd-init.yml
      when:
        - lxd_version is version('3.0', operator='ge', strict=True)
