---

- name: Debug | ansible_env
  ansible.builtin.debug:
    var: ansible_env

- import_tasks: travis.yml
  when: ansible_env['TRAVIS'] is defined and ansible_env['TRAVIS'] == 'true'

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- import_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 7

- import_tasks: redhat7.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- import_tasks: lxd.yml

- name: Get LXD Version
  ansible.builtin.command: lxd --version
  register: lxd_version_cmd
  changed_when: false

- name: Extract LXD version
  ansible.builtin.set_fact:
    lxd_version: "{{ lxd_version_cmd.stdout_lines[0] }}"

- import_tasks: lxd-init.yml
  when: lxd_version is version('3.0', operator='ge', strict=True)
